### ISSUE TITLE
!Vclink

### ISSUE THREAD

**Issue by Mr-Mr-Minecraft** [SineVector241/VoiceCraft-MCBE_ProximityChat_Addon#2]
when I do !vclink nothing happens i have checked and everything is perfect please help!

**Comment by SIsilicon** [comment]
@Mr-Mr-Minecraft I assume you've also installed and set up the app that should be used with the addon?

**Comment by DJlamps** [comment]
Same !VcLink doesnt work on the most recent version of it

**Comment by SineVector241** [comment]
Look at the guide on the other repo. its `!connect` and `!bind` now
